Repository census-instrumentation/opencensus-python, pull requests merged in 2018-07, with the labels that each got.

#233 Stats: Fix hello world example and measure_to_view_map.
  examples/stats/helloworld/main.py
  opencensus/stats/measure_to_view_map.py
  tests/unit/stats/test_measure_to_view_map.py
Labels: bug, stats

#209 Tag Propagation
  opencensus/tags/propagation/__init__.py
  opencensus/tags/propagation/binary_serializer.py
  opencensus/tags/tag_map.py
  tests/unit/tags/propagation/test_binary_serializer.py
  tests/unit/tags/test_tag_map.py
Labels: cla: no

#237 Support trace propagation in httplib integration
  opencensus/trace/ext/httplib/trace.py
  tests/unit/trace/ext/httplib/test_httplib_trace.py
Labels: cla: yes

#236 fix: jaeger trace_id conversion only uses 64 bits
  opencensus/trace/exporters/jaeger_exporter.py
  tests/unit/trace/exporters/test_jaeger_exporter.py
Labels: cla: yes

#245 Update README about building from source.
  README.rst
Labels: cla: yes
