Repository census-instrumentation/opencensus-python, pull requests merged in 2018-10, with the labels that each got.

#339 Prepare for 0.1.8 release
  opencensus/trace/exporters/stackdriver_exporter.py
  setup.py
Labels: cla: yes

#341 Make a few files non-executable
  opencensus/stats/exporters/__init__.py
  opencensus/stats/exporters/base.py
  opencensus/stats/exporters/prometheus_exporter.py
  tests/unit/stats/exporter/test_prometheus_stats.py
Labels: cla: yes

#340 README: Update stale instructions.
  README.rst
Labels: cla: yes, documentation, stats

#344 Quick fix for 3.x deprecation warnings
  tests/unit/metrics/export/test_summary.py
  tests/unit/metrics/test_label_value.py
Labels: cla: yes

#345 Bump django to 1.11.15
  requirements-test.txt
Labels: cla: yes

#325 Only use default Jaeger endpoint when no endpoint is defined
  opencensus/trace/exporters/jaeger_exporter.py
Labels: cla: yes

#329 Add Threading integration
  README.rst
  opencensus/trace/config_integration.py
  opencensus/trace/ext/threading/__init__.py
  opencensus/trace/ext/threading/trace.py
  tests/unit/trace/ext/threading/test_threading_trace.py
Labels: cla: yes

#347 Add Metric and supporting classes
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/metric_descriptor.py
  opencensus/metrics/export/time_series.py
  opencensus/metrics/export/value.py
  tests/unit/metrics/export/test_metric.py
  tests/unit/metrics/export/test_metric_descriptor.py
  tests/unit/metrics/export/test_point.py
  tests/unit/metrics/export/test_time_series.py
  tests/unit/metrics/export/test_value.py
Labels: cla: yes, metrics

#343 Improve W3C Trace Context compliance
  opencensus/trace/propagation/trace_context_http_header_format.py
  opencensus/trace/propagation/tracestate_string_format.py
  opencensus/trace/tracestate.py
  tests/unit/trace/propagation/test_trace_context_http_header_format.py
Labels: cla: yes

#354 Bump async transport _WAIT_PERIOD to 60s
  opencensus/common/transports/async.py
Labels: cla: yes

#355 Add helper class for stats/metrics conversion
  opencensus/stats/metric_utils.py
  tests/unit/stats/test_metric_utils.py
Labels: cla: yes

#362 Fix build errors
  opencensus/common/transports/async_.py
  opencensus/stats/exporters/prometheus_exporter.py
  opencensus/stats/exporters/stackdriver_exporter.py
  opencensus/trace/propagation/google_cloud_format.py
  tests/unit/common/transports/test_async.py
Labels: cla: yes

#363 Thread pools integration
  opencensus/trace/execution_context.py
  opencensus/trace/ext/threading/trace.py
  tests/unit/trace/ext/threading/test_threading_trace.py
  tests/unit/trace/test_execution_context.py
Labels: cla: yes

#369 Replace exporter version constants with package version
  opencensus/__version__.py
  opencensus/trace/exporters/ocagent/trace_exporter.py
  opencensus/trace/exporters/stackdriver_exporter.py
  setup.py
  tests/unit/trace/exporters/ocagent/test_trace_exporter.py
  tests/unit/trace/exporters/test_stackdriver_exporter.py
Labels: cla: yes

#370 Set stackdriver stats exporter user agent
  opencensus/stats/exporters/stackdriver_exporter.py
  tests/unit/stats/exporter/test_stackdriver_stats.py
Labels: cla: yes

#372 Remove manual version update step from RELEASING.md
  RELEASING.md
Labels: cla: yes

#338 Propagate tracing headers for requests module
  opencensus/trace/ext/requests/trace.py
  tests/unit/trace/ext/requests/test_requests_trace.py
Labels: cla: yes
