Repository census-instrumentation/opencensus-python, pull requests merged in 2018-08, with the labels that each got.

#246 Fix bugs in stats library
  examples/stats/helloworld/main.py
  opencensus/stats/aggregation.py
  opencensus/stats/aggregation_data.py
  opencensus/stats/view_data.py
  tests/unit/stats/test_view_data.py
Labels: cla: yes

#251 support W3C distributed tracing (part 1)
  opencensus/trace/propagation/tracestate_string_format.py
  opencensus/trace/tracestate.py
  tests/unit/trace/test_tracestate.py
Labels: cla: yes

#252 Fix typos in the README.
  README.rst
Labels: cla: yes, documentation

#259 support W3C distributed tracing (part 2)
  opencensus/trace/span.py
  opencensus/trace/span_context.py
  opencensus/trace/trace_options.py
  tests/unit/trace/test_span.py
  tests/unit/trace/test_span_context.py
Labels: cla: yes

#258 Stats: Allow recording against implicit tag_map.
  opencensus/stats/measurement_map.py
  tests/unit/stats/test_measurement_map.py
Labels: cla: yes, stats

#261 support W3C distributed tracing (part 3)
  opencensus/trace/propagation/trace_context_http_header_format.py
  tests/unit/trace/ext/httplib/test_httplib_trace.py
  tests/unit/trace/propagation/test_trace_context_http_header_format.py
Labels: cla: yes

#264 [Fixes #263] Fix gRPC client interceptor
  opencensus/trace/ext/grpc/client_interceptor.py
Labels: cla: yes

#271 Set SpanKind in extensions
  opencensus/trace/ext/dbapi/trace.py
  opencensus/trace/ext/django/middleware.py
  opencensus/trace/ext/flask/flask_middleware.py
  opencensus/trace/ext/grpc/client_interceptor.py
  opencensus/trace/ext/grpc/server_interceptor.py
  opencensus/trace/ext/httplib/trace.py
  opencensus/trace/ext/postgresql/trace.py
  opencensus/trace/ext/pyramid/pyramid_middleware.py
  opencensus/trace/ext/requests/trace.py
  opencensus/trace/ext/sqlalchemy/trace.py
  tests/unit/trace/ext/django/test_middleware.py
  tests/unit/trace/ext/flask/test_flask_middleware.py
  tests/unit/trace/ext/grpc/test_client_interceptor.py
  tests/unit/trace/ext/grpc/test_server_interceptor.py
  tests/unit/trace/ext/httplib/test_httplib_trace.py
  tests/unit/trace/ext/pyramid/test_pyramid_middleware.py
  tests/unit/trace/ext/requests/test_requests_trace.py
  tests/unit/trace/ext/sqlalchemy/test_sqlalchemy_trace.py
Labels: cla: yes

#272 Rename attributes to the default naming schema and use standard http attributes
  opencensus/trace/attributes_helper.py
  opencensus/trace/exporters/stackdriver_exporter.py
  opencensus/trace/ext/dbapi/trace.py
  opencensus/trace/ext/django/middleware.py
  opencensus/trace/ext/httplib/trace.py
  opencensus/trace/ext/postgresql/trace.py
  opencensus/trace/ext/pyramid/pyramid_middleware.py
  opencensus/trace/ext/requests/trace.py
  opencensus/trace/ext/sqlalchemy/trace.py
  tests/system/trace/django/django_system_test.py
  tests/system/trace/flask/flask_system_test.py
  tests/unit/trace/exporters/test_stackdriver_exporter.py
  tests/unit/trace/ext/django/test_middleware.py
  tests/unit/trace/ext/flask/test_flask_middleware.py
  tests/unit/trace/ext/grpc/test_client_interceptor.py
  tests/unit/trace/ext/grpc/test_server_interceptor.py
  tests/unit/trace/ext/httplib/test_httplib_trace.py
  tests/unit/trace/ext/pyramid/test_pyramid_middleware.py
  tests/unit/trace/ext/requests/test_requests_trace.py
  tests/unit/trace/ext/sqlalchemy/test_sqlalchemy_trace.py
  tests/unit/trace/test_span.py
Labels: cla: yes

#253 Fix bug in updating aggregation map.
  examples/stats/helloworld/main.py
  opencensus/stats/view_data.py
  tests/unit/stats/test_view_data.py
Labels: cla: yes, stats

#262 Document 'google-cloud-trace' and BackgroundThreadTransport
  README.rst
Labels: cla: yes

#256 Stats core changes
  examples/stats/helloworld/main.py
  opencensus/common/__init__.py
  opencensus/common/transports/__init__.py
  opencensus/common/transports/async.py
  opencensus/common/transports/base.py
  opencensus/common/transports/sync.py
  opencensus/stats/aggregation.py
  opencensus/stats/aggregation_data.py
  opencensus/stats/measure_to_view_map.py
  opencensus/stats/view_manager.py
  tests/unit/common/transports/test_async.py
  tests/unit/common/transports/test_common_base_transport.py
  tests/unit/common/transports/test_sync.py
  tests/unit/stats/test_aggregation.py
  tests/unit/stats/test_aggregation_data.py
  tests/unit/stats/test_measure_to_view_map.py
  tests/unit/stats/test_view_manager.py
Labels: cla: yes

#290 Enable the configuration of https
  README.rst
  docs/trace/usage.rst
  opencensus/trace/exporters/zipkin_exporter.py
  opencensus/trace/ext/django/config.py
  opencensus/trace/ext/django/middleware.py
  opencensus/trace/ext/flask/flask_middleware.py
  tests/unit/trace/ext/django/test_config.py
  tests/unit/trace/ext/django/test_middleware.py
  tests/unit/trace/ext/flask/test_flask_middleware.py
Labels: cla: yes

#287 Stats exemplars
  opencensus/stats/aggregation_data.py
  opencensus/stats/measure_to_view_map.py
  opencensus/stats/measurement_map.py
  opencensus/stats/view_data.py
  tests/unit/stats/test_aggregation_data.py
  tests/unit/stats/test_measure_to_view_map.py
  tests/unit/stats/test_measurement_map.py
  tests/unit/stats/test_view_data.py
Labels: cla: yes
