Repository census-instrumentation/opencensus-python, pull requests merged in 2019-04, with the labels that each got.

#577 Switch SD exporter to polling
  README.rst
  contrib/opencensus-ext-prometheus/README.rst
  contrib/opencensus-ext-prometheus/examples/prometheus.py
  contrib/opencensus-ext-prometheus/tests/test_prometheus_stats.py
  contrib/opencensus-ext-stackdriver/README.rst
  contrib/opencensus-ext-stackdriver/examples/stackdriver.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  examples/stats/helloworld/main.py
  opencensus/metrics/transport.py
  opencensus/stats/stats.py
  tests/system/stats/prometheus/prometheus_stats_test.py
  tests/system/stats/stackdriver/stackdriver_stats_test.py
  tests/unit/metrics/test_transport.py
  tests/unit/stats/test_stats.py
Labels: GA-Effort, breaking change, cla: yes, exporters, metrics

#474 span context: set the default recorded flag to 0, and fix default trace options bug
  contrib/opencensus-ext-jaeger/tests/test_jaeger_exporter.py
  opencensus/trace/span_context.py
  tests/unit/trace/test_tracer.py
Labels: cla: yes

#593 Stackdriver poll-based metrics
  README.rst
  contrib/opencensus-ext-prometheus/README.rst
  contrib/opencensus-ext-prometheus/examples/prometheus.py
  contrib/opencensus-ext-prometheus/tests/test_prometheus_stats.py
  contrib/opencensus-ext-stackdriver/README.rst
  contrib/opencensus-ext-stackdriver/examples/stackdriver.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  examples/stats/helloworld/main.py
  opencensus/metrics/transport.py
  opencensus/stats/measure_to_view_map.py
  opencensus/stats/stats.py
  tests/system/stats/prometheus/prometheus_stats_test.py
  tests/system/stats/stackdriver/stackdriver_stats_test.py
  tests/unit/metrics/test_transport.py
  tests/unit/stats/test_stats.py
Labels: GA-Effort, breaking change, cla: yes, exporters, metrics, stats

#599 RuntimeContext improvement
  .coveragerc
  context/opencensus-context/opencensus/common/runtime_context/__init__.py
  context/opencensus-context/setup.py
  context/opencensus-context/tests/test_runtime_context.py
  nox.py
Labels: cla: yes

#602 Minor refactor Tags
  contrib/opencensus-ext-postgresql/setup.py
  opencensus/stats/measurement_map.py
  opencensus/tags/__init__.py
  opencensus/tags/execution_context.py
  opencensus/tags/tag.py
  opencensus/tags/tag_key.py
  opencensus/tags/tag_value.py
  tests/unit/stats/test_measurement_map.py
  tests/unit/tags/test_tag.py
  tests/unit/tags/test_tag_execution_context.py
  tests/unit/tags/test_tag_map.py
Labels: GA-Effort, cla: yes, tags

#605 Don't return transport along with SD stats exporter
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  tests/system/stats/stackdriver/stackdriver_stats_test.py
Labels: GA-Effort, breaking change, cla: yes, exporters

#603 Prevent middleware error on older Django versions (<1.8)
  contrib/opencensus-ext-django/opencensus/ext/django/middleware.py
  contrib/opencensus-ext-django/tests/test_django_middleware.py
Labels: cla: yes

#606 v0.4.x master version updates
  CHANGELOG.md
  context/opencensus-context/CHANGELOG.md
  context/opencensus-context/version.py
  contrib/opencensus-ext-dbapi/CHANGELOG.md
  contrib/opencensus-ext-dbapi/setup.py
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-django/version.py
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-flask/version.py
  contrib/opencensus-ext-google-cloud-clientlibs/CHANGELOG.md
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-httplib/setup.py
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-jaeger/version.py
  contrib/opencensus-ext-mysql/CHANGELOG.md
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-ocagent/version.py
  contrib/opencensus-ext-postgresql/CHANGELOG.md
  contrib/opencensus-ext-postgresql/setup.py
  contrib/opencensus-ext-prometheus/CHANGELOG.md
  contrib/opencensus-ext-prometheus/setup.py
  contrib/opencensus-ext-prometheus/version.py
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymysql/CHANGELOG.md
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pyramid/CHANGELOG.md
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-pyramid/version.py
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/setup.py
  contrib/opencensus-ext-sqlalchemy/CHANGELOG.md
  contrib/opencensus-ext-sqlalchemy/setup.py
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-stackdriver/version.py
  contrib/opencensus-ext-threading/CHANGELOG.md
  contrib/opencensus-ext-threading/setup.py
  contrib/opencensus-ext-zipkin/CHANGELOG.md
  contrib/opencensus-ext-zipkin/setup.py
  contrib/opencensus-ext-zipkin/version.py
  opencensus/common/version/__init__.py
  setup.py
Labels: cla: yes, release

#607 Don't exit on twine upload failures
  scripts/twine_upload.sh
Labels: cla: yes, meta

#610 Use default auth for StackdriverStatsExporter
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
Labels: cla: yes, exporters

#611 Allow empty `MetricDescriptor.label_keys`
  opencensus/metrics/export/metric_descriptor.py
  tests/unit/metrics/export/test_metric_descriptor.py
Labels: cla: yes

#595 Allow to pass x-b3-sampled as string
  opencensus/trace/propagation/b3_format.py
  tests/unit/trace/propagation/test_b3_format.py
Labels: cla: yes

#614 Allow for empty label values
  opencensus/metrics/export/time_series.py
  tests/unit/metrics/export/test_time_series.py
  tests/unit/stats/test_metric_utils.py
Labels: bug, cla: yes, metrics

#615 v0.4.1 and stackdriver v0.2.1 release
  CHANGELOG.md
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  contrib/opencensus-ext-stackdriver/version.py
  opencensus/common/version/__init__.py
  opencensus/metrics/export/metric_descriptor.py
  opencensus/metrics/export/time_series.py
  opencensus/trace/propagation/b3_format.py
  tests/unit/metrics/export/test_metric_descriptor.py
  tests/unit/metrics/export/test_time_series.py
  tests/unit/stats/test_metric_utils.py
  tests/unit/trace/propagation/test_b3_format.py
Labels: cla: yes, exporters, release

#596 Remove vendor proto files and use opencensus-proto instead.
  .coveragerc
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/v1/common_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/trace_service_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/trace_service_pb2_grpc.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/v1/resource_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/trace_config_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/trace_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/utils.py
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter_utils.py
Labels: cla: yes, exporters, ext, tech debt

#618 Make wait_period configurable in async transport
  contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py
  contrib/opencensus-ext-azure/tests/test_azure_trace_exporter.py
  opencensus/common/transports/async_.py
  tests/unit/common/transports/test_async.py
Labels: cla: yes

#619 Change algorithm for span ID generation
  opencensus/trace/span_context.py
Labels: cla: yes

#620 Don't use time in trace ID creation
  opencensus/trace/span_context.py
Labels: cla: yes

#622 Respect default labels in StackdriverStatsExporter
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
Labels: bug, cla: yes, exporters

#617 Add ocagent stats exporter.
  README.rst
  contrib/opencensus-ext-google-cloud-clientlibs/tests/test_google_cloud_clientlibs_trace.py
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-grpc/opencensus/ext/grpc/client_interceptor.py
  contrib/opencensus-ext-grpc/opencensus/ext/grpc/utils.py
  contrib/opencensus-ext-grpc/tests/test_client_interceptor.py
  contrib/opencensus-ext-grpc/tests/test_server_interceptor.py
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/README.rst
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/stats_exporter/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/utils.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/utils/__init__.py
  contrib/opencensus-ext-ocagent/tests/test_ocagent_utils.py
  contrib/opencensus-ext-ocagent/tests/test_stats_exporter.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter_utils.py
Labels: cla: yes

#624 Refactor Django/Pyramid configuration
  README.rst
  contrib/opencensus-ext-azure/examples/client.py
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-django/README.rst
  contrib/opencensus-ext-django/examples/app/settings.py
  contrib/opencensus-ext-django/opencensus/ext/django/config.py
  contrib/opencensus-ext-django/opencensus/ext/django/middleware.py
  contrib/opencensus-ext-django/tests/test_django_config.py
  contrib/opencensus-ext-django/tests/test_django_middleware.py
  contrib/opencensus-ext-pyramid/CHANGELOG.md
  contrib/opencensus-ext-pyramid/README.rst
  contrib/opencensus-ext-pyramid/examples/__init__.py
  contrib/opencensus-ext-pyramid/examples/simple.py
  contrib/opencensus-ext-pyramid/opencensus/ext/pyramid/config.py
  contrib/opencensus-ext-pyramid/opencensus/ext/pyramid/pyramid_middleware.py
  contrib/opencensus-ext-pyramid/tests/test_pyramid_config.py
  contrib/opencensus-ext-pyramid/tests/test_pyramid_middleware.py
  opencensus/trace/tracer.py
  tests/system/trace/django/app/settings.py
  tests/unit/trace/test_tracer.py
Labels: breaking change, cla: yes

#626 Cumulative gauges
  CHANGELOG.md
  opencensus/metrics/export/cumulative.py
  opencensus/metrics/export/gauge.py
  tests/unit/metrics/export/test_cumulative.py
  tests/unit/metrics/export/test_gauge.py
Labels: GA-Effort, cla: yes, metrics

#629 Docs
  README.rst
  context/opencensus-context/README.rst
Labels: cla: yes

#631 Update versions and changelogs for v0.5.0 release
  CHANGELOG.md
  context/opencensus-context/CHANGELOG.md
  contrib/opencensus-ext-azure/CHANGELOG.md
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/version.py
  contrib/opencensus-ext-azure/setup.py
  contrib/opencensus-ext-dbapi/CHANGELOG.md
  contrib/opencensus-ext-dbapi/setup.py
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-django/version.py
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-flask/version.py
  contrib/opencensus-ext-google-cloud-clientlibs/CHANGELOG.md
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-grpc/version.py
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-httplib/setup.py
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-mysql/CHANGELOG.md
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-ocagent/version.py
  contrib/opencensus-ext-postgresql/CHANGELOG.md
  contrib/opencensus-ext-postgresql/setup.py
  contrib/opencensus-ext-prometheus/CHANGELOG.md
  contrib/opencensus-ext-prometheus/setup.py
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymysql/CHANGELOG.md
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pyramid/CHANGELOG.md
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-pyramid/version.py
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/setup.py
  contrib/opencensus-ext-sqlalchemy/CHANGELOG.md
  contrib/opencensus-ext-sqlalchemy/setup.py
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-stackdriver/version.py
  contrib/opencensus-ext-threading/CHANGELOG.md
  contrib/opencensus-ext-threading/setup.py
  contrib/opencensus-ext-zipkin/CHANGELOG.md
  contrib/opencensus-ext-zipkin/setup.py
  opencensus/common/version/__init__.py
Labels: cla: yes

#632 Introduce persistent storage to Azure exporter
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/__init__.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/storage.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py
  contrib/opencensus-ext-azure/tests/test_azure_trace_exporter.py
  contrib/opencensus-ext-azure/tests/test_storage.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  nox.py
  opencensus/common/schedule/__init__.py
  opencensus/metrics/transport.py
  tests/unit/metrics/test_transport.py
Labels: cla: yes

#635 Improve test process
  AUTHORS
  contrib/opencensus-ext-ocagent/tests/test_ocagent_utils.py
  contrib/opencensus-ext-ocagent/tests/test_stats_exporter.py
  nox.py
  requirements-test.txt
  tests/unit/common/monitored_resource_util/test_aws_identity_doc_utils.py
  tests/unit/common/monitored_resource_util/test_gcp_metadata_config.py
  tests/unit/trace/test_blank_span.py
  tox.ini
Labels: cla: yes

#637 Use third party mock
  tests/unit/common/monitored_resource_util/test_k8s_utils.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
  tests/unit/common/test_resource.py
  tests/unit/log/test_log.py
  tests/unit/stats/test_metric_utils.py
Labels: cla: yes

#634 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes, meta

#638 Cleanup
  CHANGELOG.md
  CONTRIBUTING.md
  README.rst
  contrib/opencensus-ext-azure/CHANGELOG.md
Labels: cla: yes
