Repository census-instrumentation/opencensus-python, pull requests merged in 2019-05, with the labels that each got.

#640 Update azure ctor, docs and samples
  contrib/opencensus-ext-azure/CHANGELOG.md
  contrib/opencensus-ext-azure/README.rst
  contrib/opencensus-ext-azure/examples/client.py
  contrib/opencensus-ext-azure/examples/config.py
  contrib/opencensus-ext-azure/examples/custom.py
  contrib/opencensus-ext-azure/examples/server.py
  contrib/opencensus-ext-azure/examples/simple.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py
  contrib/opencensus-ext-azure/tests/test_azure_trace_exporter.py
Labels: cla: yes

#639 Override sampling decision
  CHANGELOG.md
  README.rst
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-django/opencensus/ext/django/middleware.py
  contrib/opencensus-ext-django/tests/test_django_middleware.py
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/examples/custom.py
  contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-grpc/examples/hello_world_server.py
  contrib/opencensus-ext-pyramid/README.rst
  contrib/opencensus-ext-pyramid/examples/simple.py
  contrib/opencensus-ext-pyramid/opencensus/ext/pyramid/config.py
  contrib/opencensus-ext-pyramid/tests/test_pyramid_middleware.py
  docs/trace/api/always_off_sampler.rst
  docs/trace/api/always_on_sampler.rst
  docs/trace/api/probability_sampler.rst
  docs/trace/api/samplers.rst
  docs/trace/usage.rst
  examples/trace/helloworld/main.py
  opencensus/log/__init__.py
  opencensus/trace/samplers/__init__.py
  opencensus/trace/samplers/always_off.py
  opencensus/trace/samplers/always_on.py
  opencensus/trace/samplers/base.py
  opencensus/trace/samplers/probability.py
  opencensus/trace/trace_options.py
  opencensus/trace/tracer.py
  tests/system/trace/basic_trace/basic_trace_system_test.py
  tests/system/trace/django/app/settings.py
  tests/unit/log/test_log.py
  tests/unit/trace/samplers/test_always_off.py
  tests/unit/trace/samplers/test_always_on.py
  tests/unit/trace/samplers/test_base_sampler.py
  tests/unit/trace/samplers/test_probability.py
  tests/unit/trace/test_tracer.py
Labels: GA-Effort, breaking change, cla: yes

#641 Minor cleanup
  AUTHORS
  README.rst
  nox.py
  setup.py
Labels: cla: yes

#636 Add package to provide gevent compatibiliy (#628)
  README.rst
  contrib/opencensus-ext-gevent/CHANGELOG.md
  contrib/opencensus-ext-gevent/README.rst
  contrib/opencensus-ext-gevent/opencensus/__init__.py
  contrib/opencensus-ext-gevent/opencensus/ext/__init__.py
  contrib/opencensus-ext-gevent/opencensus/ext/gevent/__init__.py
  contrib/opencensus-ext-gevent/opencensus/ext/gevent/geventcompatibility.py
  contrib/opencensus-ext-gevent/setup.cfg
  contrib/opencensus-ext-gevent/setup.py
  contrib/opencensus-ext-gevent/tests/test_patching.py
  contrib/opencensus-ext-gevent/version.py
  nox.py
Labels: cla: yes, enhancement, ext, trace

#646 Add contribute message for python versions
  CONTRIBUTING.md
Labels: cla: yes

#644 Add details about aggregation pipelines & avoid get(default) parameter
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/opencensus/ext/pymongo/trace.py
  contrib/opencensus-ext-pymongo/tests/test_pymongo_trace.py
Labels: cla: yes

#652 Pin nox-automation, make noxfile explicit
  .travis.yml
Labels: cla: yes

#653 Replace nox-automation with nox
  .circleci/config.yml
  .travis.yml
  CONTRIBUTING.md
  noxfile.py
Labels: cla: yes

#649 Limit span attachments
  contrib/opencensus-ext-azure/tests/test_azure_trace_exporter.py
  contrib/opencensus-ext-grpc/opencensus/ext/grpc/utils.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py
  contrib/opencensus-ext-jaeger/tests/test_jaeger_exporter.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/utils.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter_utils.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_exporter.py
  contrib/opencensus-ext-zipkin/opencensus/ext/zipkin/trace_exporter/__init__.py
  contrib/opencensus-ext-zipkin/tests/test_zipkin_exporter.py
  opencensus/trace/base_span.py
  opencensus/trace/blank_span.py
  opencensus/trace/span.py
  opencensus/trace/span_data.py
  opencensus/trace/time_event.py
  opencensus/trace/tracers/context_tracer.py
  tests/unit/trace/exporters/test_logging_exporter.py
  tests/unit/trace/test_base_span.py
  tests/unit/trace/test_blank_span.py
  tests/unit/trace/test_span.py
  tests/unit/trace/test_span_data.py
  tests/unit/trace/test_time_event.py
  tests/unit/trace/test_tracer.py
  tests/unit/trace/tracers/test_context_tracer.py
Labels: GA-Effort, breaking change, cla: yes

#642 Refactor async exporter
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/__init__.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/exporter.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py
  contrib/opencensus-ext-azure/tests/test_azure_trace_exporter.py
  opencensus/common/schedule/__init__.py
  tests/unit/common/test_schedule.py
Labels: cla: yes, enhancement, exporters, ext

#654 Clean up
  CONTRIBUTING.md
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py
  contrib/opencensus-ext-jaeger/tests/test_jaeger_exporter.py
  contrib/opencensus-ext-zipkin/opencensus/ext/zipkin/trace_exporter/__init__.py
  opencensus/trace/propagation/google_cloud_format.py
  opencensus/trace/span_context.py
  opencensus/trace/trace_options.py
Labels: cla: yes

#656 Fix stackdriver k8s label keys
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/trace_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_exporter.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  opencensus/common/monitored_resource/aws_identity_doc_utils.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
Labels: bug, cla: yes, exporters

#655 Move logging integration into ext package
  README.rst
  contrib/opencensus-ext-logging/CHANGELOG.md
  contrib/opencensus-ext-logging/README.rst
  contrib/opencensus-ext-logging/opencensus/__init__.py
  contrib/opencensus-ext-logging/opencensus/ext/__init__.py
  contrib/opencensus-ext-logging/opencensus/ext/logging/__init__.py
  contrib/opencensus-ext-logging/opencensus/ext/logging/trace.py
  contrib/opencensus-ext-logging/setup.cfg
  contrib/opencensus-ext-logging/setup.py
  contrib/opencensus-ext-logging/tests/test_logging_integration.py
  contrib/opencensus-ext-logging/version.py
  noxfile.py
  opencensus/log/__init__.py
  tests/unit/log/test_log.py
Labels: cla: yes

#659 Use httplib's host property instead of urllib3's _dns_host
  contrib/opencensus-ext-httplib/opencensus/ext/httplib/trace.py
  contrib/opencensus-ext-httplib/tests/test_httplib_trace.py
Labels: cla: yes

#662 Trav
  .travis.yml
  tox.ini
Labels: cla: yes

#657 Skeleton for Azure Log Exporter
  README.rst
  contrib/opencensus-ext-azure/CHANGELOG.md
  contrib/opencensus-ext-azure/README.rst
  contrib/opencensus-ext-azure/examples/logs/correlated.py
  contrib/opencensus-ext-azure/examples/logs/simple.py
  contrib/opencensus-ext-azure/examples/traces/client.py
  contrib/opencensus-ext-azure/examples/traces/config.py
  contrib/opencensus-ext-azure/examples/traces/custom.py
  contrib/opencensus-ext-azure/examples/traces/server.py
  contrib/opencensus-ext-azure/examples/traces/simple.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/exporter.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/log_exporter/__init__.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py
  contrib/opencensus-ext-azure/tests/test_azure_trace_exporter.py
  contrib/opencensus-ext-logging/README.rst
  opencensus/common/schedule/__init__.py
  tests/unit/common/test_schedule.py
Labels: azure, cla: yes, logging

#665 Add Python 3.7 for Travis
  .travis.yml
  tox.ini
Labels: cla: yes

#449 Remove well_known_types.Error and well_known_types.ParseError.
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/utils/__init__.py
Labels: cla: yes
