Repository census-instrumentation/opencensus-python, pull requests merged in 2019-03, with the labels that each got.

#531 refactor namespace package - add test integration and release for contrib package
  .coveragerc
  contrib/opencensus-correlation/CHANGELOG.md
  contrib/opencensus-correlation/README.rst
  contrib/opencensus-correlation/opencensus/__init__.py
  contrib/opencensus-correlation/opencensus/common/__init__.py
  contrib/opencensus-correlation/opencensus/common/correlationcontext/__init__.py
  contrib/opencensus-correlation/opencensus/common/correlationcontext/correlationcontext.py
  contrib/opencensus-correlation/setup.cfg
  contrib/opencensus-correlation/setup.py
  contrib/opencensus-correlation/tests/__init__.py
  contrib/opencensus-correlation/tests/test_correlation_context.py
  contrib/opencensus-correlation/version.py
  docs/requirements.txt
  nox.py
  scripts/twine_upload.sh
  setup.py
Labels: cla: yes

#528 Replace gke_container with k8s_container for stackdriver
  CHANGELOG.md
  opencensus/common/monitored_resource/gcp_metadata_config.py
  opencensus/common/monitored_resource/k8s_utils.py
  opencensus/common/monitored_resource/monitored_resource.py
  tests/unit/common/monitored_resource_util/test_gcp_metadata_config.py
  tests/unit/common/monitored_resource_util/test_k8s_utils.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
Labels: GA-Effort, cla: yes, resources

#532 componentize trace.ext.flask
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/README.rst
  contrib/opencensus-ext-flask/opencensus/__init__.py
  contrib/opencensus-ext-flask/opencensus/ext/__init__.py
  contrib/opencensus-ext-flask/opencensus/ext/flask/__init__.py
  contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py
  contrib/opencensus-ext-flask/setup.cfg
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-flask/version.py
  nox.py
  opencensus/trace/ext/flask/__init__.py
  requirements-test.txt
  tests/system/trace/flask/main.py
Labels: breaking change, cla: yes

#534 fix zone value in monitored resource
  opencensus/common/monitored_resource/gcp_metadata_config.py
  tests/unit/common/monitored_resource_util/test_gcp_metadata_config.py
Labels: cla: yes

#541 refactor namespace package - docs and samples
  README.rst
  contrib/opencensus-ext-django/examples/app/__init__.py
  contrib/opencensus-ext-django/examples/app/forms.py
  contrib/opencensus-ext-django/examples/app/settings.py
  contrib/opencensus-ext-django/examples/app/templates/home.html
  contrib/opencensus-ext-django/examples/app/urls.py
  contrib/opencensus-ext-django/examples/app/views.py
  contrib/opencensus-ext-django/examples/manage.py
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-flask/examples/custom.py
  contrib/opencensus-ext-flask/examples/simple.py
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/README.rst
  contrib/opencensus-ext-grpc/README.rst
  contrib/opencensus-ext-grpc/examples/hello_world.proto
  contrib/opencensus-ext-grpc/examples/hello_world_client.py
  contrib/opencensus-ext-grpc/examples/hello_world_pb2.py
  contrib/opencensus-ext-grpc/examples/hello_world_pb2_grpc.py
  contrib/opencensus-ext-grpc/examples/hello_world_server.py
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-httplib/README.rst
  contrib/opencensus-ext-mysql/README.rst
  contrib/opencensus-ext-postgresql/README.rst
  contrib/opencensus-ext-pyramid/examples/__init__.py
  contrib/opencensus-ext-pyramid/examples/app/__init__.py
  contrib/opencensus-ext-pyramid/examples/simple.py
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-requests/README.rst
  contrib/opencensus-ext-sqlalchemy/README.rst
  contrib/opencensus-ext-threading/README.rst
  docs/trace/usage.rst
  requirements-test.txt
  setup.py
Labels: cla: yes

#545 Fix subspan export bug
  opencensus/trace/tracers/context_tracer.py
  tests/system/trace/basic_trace/basic_trace_system_test.py
  tests/unit/trace/tracers/test_context_tracer.py
Labels: cla: yes

#543 Integrate with pymongo
  README.rst
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/README.rst
  contrib/opencensus-ext-pymongo/opencensus/__init__.py
  contrib/opencensus-ext-pymongo/opencensus/ext/__init__.py
  contrib/opencensus-ext-pymongo/opencensus/ext/pymongo/__init__.py
  contrib/opencensus-ext-pymongo/opencensus/ext/pymongo/trace.py
  contrib/opencensus-ext-pymongo/setup.cfg
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymongo/tests/test_pymongo_trace.py
  contrib/opencensus-ext-pymongo/version.py
  nox.py
  opencensus/trace/config_integration.py
Labels: cla: yes

#536 Add TraceLogger
  opencensus/log/__init__.py
  requirements-test.txt
  tests/unit/log/test_log.py
Labels: cla: yes, logging

#546 refactor namespace package - componentize ocagent trace exporter
  contrib/opencensus-ext-django/tests/test_django_middleware.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/README.rst
  contrib/opencensus-ext-ocagent/opencensus/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/v1/common_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/trace_service_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/trace_service_pb2_grpc.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/v1/resource_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/trace_config_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/trace_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/utils.py
  contrib/opencensus-ext-ocagent/setup.cfg
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter.py
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter_utils.py
  contrib/opencensus-ext-ocagent/version.py
  nox.py
Labels: breaking change, cla: yes

#548 Refactor config_integration
  opencensus/trace/config_integration.py
Labels: cla: yes

#515 Merge custom resources on detection
  opencensus/common/monitored_resource/monitored_resource.py
  opencensus/common/resource/__init__.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
  tests/unit/common/test_resource.py
Labels: GA-Effort, cla: yes, resources

#539 Fix gRPC client interceptor for channels reused across traces
  CHANGELOG.md
  contrib/opencensus-ext-google-cloud-clientlibs/opencensus/ext/google_cloud_clientlibs/trace.py
  contrib/opencensus-ext-google-cloud-clientlibs/tests/test_google_cloud_clientlibs_trace.py
  contrib/opencensus-ext-grpc/opencensus/ext/grpc/client_interceptor.py
  contrib/opencensus-ext-grpc/tests/test_client_interceptor.py
Labels: cla: yes

#550 Refactor exporters into ext packages
  README.rst
  contrib/opencensus-ext-django/examples/app/settings.py
  contrib/opencensus-ext-django/tests/test_django_middleware.py
  contrib/opencensus-ext-flask/examples/custom.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-grpc/examples/hello_world_client.py
  contrib/opencensus-ext-grpc/examples/hello_world_server.py
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-jaeger/README.rst
  contrib/opencensus-ext-jaeger/opencensus/__init__.py
  contrib/opencensus-ext-jaeger/opencensus/ext/__init__.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/__init__.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/gen/__init__.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/gen/jaeger/__init__.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/gen/jaeger/agent.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/gen/jaeger/jaeger.py
  contrib/opencensus-ext-jaeger/setup.cfg
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-jaeger/tests/test_jaeger_exporter.py
  contrib/opencensus-ext-jaeger/version.py
  contrib/opencensus-ext-pyramid/tests/test_pyramid_middleware.py
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/README.rst
  contrib/opencensus-ext-stackdriver/opencensus/__init__.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/__init__.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/__init__.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/trace_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/setup.cfg
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_exporter.py
  contrib/opencensus-ext-stackdriver/version.py
  contrib/opencensus-ext-zipkin/CHANGELOG.md
  contrib/opencensus-ext-zipkin/README.rst
  contrib/opencensus-ext-zipkin/opencensus/__init__.py
  contrib/opencensus-ext-zipkin/opencensus/ext/__init__.py
  contrib/opencensus-ext-zipkin/opencensus/ext/zipkin/__init__.py
  contrib/opencensus-ext-zipkin/opencensus/ext/zipkin/trace_exporter/__init__.py
  contrib/opencensus-ext-zipkin/setup.cfg
  contrib/opencensus-ext-zipkin/setup.py
  contrib/opencensus-ext-zipkin/tests/test_zipkin_exporter.py
  contrib/opencensus-ext-zipkin/version.py
  docs/trace/api/stackdriver_exporter.rst
  docs/trace/api/zipkin_exporter.rst
  docs/trace/usage.rst
  nox.py
  tests/system/trace/django/app/settings.py
  tests/system/trace/flask/main.py
Labels: breaking change, cla: yes

#552 Replace isoformat with strftime
  contrib/opencensus-ext-ocagent/tests/test_trace_exporter_utils.py
  opencensus/common/utils/__init__.py
  opencensus/stats/measurement_map.py
  opencensus/stats/view_data.py
  opencensus/stats/view_manager.py
  opencensus/trace/span.py
  opencensus/trace/time_event.py
  tests/unit/stats/exporters/test_stackdriver_stats.py
  tests/unit/stats/test_view_data.py
  tests/unit/trace/test_blank_span.py
  tests/unit/trace/test_span.py
  tests/unit/trace/test_span_data.py
  tests/unit/trace/test_time_event.py
  tests/unit/trace/test_tracer.py
Labels: cla: yes

#553 Drop opencensus-correlation dependency for release
  setup.py
Labels: cla: yes

#554 Prepare for 0.3.0 release
  CHANGELOG.md
  contrib/opencensus-correlation/version.py
  contrib/opencensus-ext-dbapi/setup.py
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-httplib/setup.py
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-postgresql/setup.py
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-requests/setup.py
  contrib/opencensus-ext-sqlalchemy/setup.py
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-threading/setup.py
  contrib/opencensus-ext-zipkin/setup.py
  opencensus/common/version/__init__.py
Labels: cla: yes

#555 v0.3.x master version updates
  CHANGELOG.md
  contrib/opencensus-correlation/version.py
  contrib/opencensus-ext-dbapi/setup.py
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-httplib/setup.py
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-postgresql/setup.py
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-requests/setup.py
  contrib/opencensus-ext-sqlalchemy/setup.py
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-threading/setup.py
  contrib/opencensus-ext-zipkin/setup.py
  opencensus/common/version/__init__.py
Labels: cla: yes

#551 Move built-in exporters to opencensus.trace
  README.rst
  contrib/opencensus-ext-django/README.rst
  contrib/opencensus-ext-django/opencensus/ext/django/config.py
  contrib/opencensus-ext-django/tests/test_django_middleware.py
  contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/__init__.py
  contrib/opencensus-ext-pyramid/README.rst
  contrib/opencensus-ext-pyramid/examples/simple.py
  contrib/opencensus-ext-pyramid/opencensus/ext/pyramid/config.py
  contrib/opencensus-ext-pyramid/tests/test_pyramid_middleware.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/trace_exporter/__init__.py
  contrib/opencensus-ext-zipkin/opencensus/ext/zipkin/trace_exporter/__init__.py
  docs/trace/api/file_exporter.rst
  docs/trace/api/logging_exporter.rst
  docs/trace/api/print_exporter.rst
  docs/trace/usage.rst
  examples/trace/helloworld/main.py
  opencensus/common/transports/async_.py
  opencensus/trace/base_exporter.py
  opencensus/trace/exporters/__init__.py
  opencensus/trace/file_exporter.py
  opencensus/trace/logging_exporter.py
  opencensus/trace/print_exporter.py
  opencensus/trace/tracer.py
  opencensus/trace/tracers/context_tracer.py
  tests/system/trace/basic_trace/basic_trace_system_test.py
  tests/unit/trace/exporters/test_base_exporter.py
  tests/unit/trace/exporters/test_file_exporter.py
  tests/unit/trace/exporters/test_logging_exporter.py
  tests/unit/trace/exporters/test_print_exporter.py
  tests/unit/trace/test_tracer.py
  tests/unit/trace/tracers/test_context_tracer.py
Labels: breaking change, cla: yes

#557 Clean up package specific dependencies
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-stackdriver/setup.py
  requirements-test.txt
  setup.py
Labels: cla: yes

#559 Fix Metric repr for ValueDistributions
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/time_series.py
  opencensus/metrics/export/value.py
Labels: GA-Effort, cla: yes

#563 Update ext dev package versions for 0.1.0 releases
  contrib/opencensus-correlation/version.py
  contrib/opencensus-ext-dbapi/version.py
  contrib/opencensus-ext-django/version.py
  contrib/opencensus-ext-flask/version.py
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/version.py
  contrib/opencensus-ext-grpc/version.py
  contrib/opencensus-ext-httplib/version.py
  contrib/opencensus-ext-jaeger/version.py
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-mysql/version.py
  contrib/opencensus-ext-ocagent/version.py
  contrib/opencensus-ext-postgresql/version.py
  contrib/opencensus-ext-prometheus/version.py
  contrib/opencensus-ext-pymongo/version.py
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pymysql/version.py
  contrib/opencensus-ext-pyramid/version.py
  contrib/opencensus-ext-requests/version.py
  contrib/opencensus-ext-sqlalchemy/version.py
  contrib/opencensus-ext-stackdriver/version.py
  contrib/opencensus-ext-threading/version.py
  contrib/opencensus-ext-zipkin/version.py
Labels: cla: yes

#568 fix lint
  contrib/opencensus-correlation/opencensus/common/correlationcontext/__init__.py
  contrib/opencensus-correlation/opencensus/common/correlationcontext/correlationcontext.py
  contrib/opencensus-correlation/setup.py
  contrib/opencensus-correlation/tests/test_correlation_context.py
  contrib/opencensus-ext-dbapi/setup.py
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-httplib/setup.py
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-postgresql/setup.py
  contrib/opencensus-ext-prometheus/setup.py
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-requests/setup.py
  contrib/opencensus-ext-sqlalchemy/setup.py
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-threading/setup.py
  contrib/opencensus-ext-zipkin/setup.py
  nox.py
Labels: cla: yes

#569 Use utcnow instead of now
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/__init__.py
  opencensus/metrics/export/gauge.py
  opencensus/stats/stats.py
  tests/unit/trace/test_blank_span.py
  tests/unit/trace/test_span.py
Labels: bug, cla: yes

#571 Use new GCP project credentials
  tests/system/credentials.json.enc
Labels: cla: yes

#570 Add cosmetic badges to ext packages
  contrib/opencensus-correlation/README.rst
  contrib/opencensus-ext-dbapi/README.rst
  contrib/opencensus-ext-django/README.rst
  contrib/opencensus-ext-flask/README.rst
  contrib/opencensus-ext-google-cloud-clientlibs/README.rst
  contrib/opencensus-ext-grpc/README.rst
  contrib/opencensus-ext-httplib/README.rst
  contrib/opencensus-ext-jaeger/README.rst
  contrib/opencensus-ext-mysql/README.rst
  contrib/opencensus-ext-ocagent/README.rst
  contrib/opencensus-ext-postgresql/README.rst
  contrib/opencensus-ext-prometheus/README.rst
  contrib/opencensus-ext-pymongo/README.rst
  contrib/opencensus-ext-pymysql/README.rst
  contrib/opencensus-ext-pyramid/README.rst
  contrib/opencensus-ext-requests/README.rst
  contrib/opencensus-ext-sqlalchemy/README.rst
  contrib/opencensus-ext-stackdriver/README.rst
  contrib/opencensus-ext-threading/README.rst
  contrib/opencensus-ext-zipkin/README.rst
Labels: cla: yes

#566 Introduce a generic context
  context/opencensus-context/CHANGELOG.md
  context/opencensus-context/README.rst
  context/opencensus-context/examples/async_span.py
  context/opencensus-context/examples/explicit_threading.py
  context/opencensus-context/examples/py27.py
  context/opencensus-context/examples/py37.py
  context/opencensus-context/examples/span.py
  context/opencensus-context/examples/thread_pool.py
  context/opencensus-context/opencensus/__init__.py
  context/opencensus-context/opencensus/common/__init__.py
  context/opencensus-context/opencensus/common/runtime_context/__init__.py
  context/opencensus-context/setup.cfg
  context/opencensus-context/setup.py
  context/opencensus-context/tests/test_runtime_context.py
  context/opencensus-context/version.py
  docs/requirements.txt
  nox.py
  scripts/twine_upload.sh
Labels: cla: yes

#575 Update contrib changelogs
  contrib/opencensus-ext-dbapi/CHANGELOG.md
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-google-cloud-clientlibs/CHANGELOG.md
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-mysql/CHANGELOG.md
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-postgresql/CHANGELOG.md
  contrib/opencensus-ext-prometheus/CHANGELOG.md
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymysql/CHANGELOG.md
  contrib/opencensus-ext-pyramid/CHANGELOG.md
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-sqlalchemy/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-threading/CHANGELOG.md
  contrib/opencensus-ext-zipkin/CHANGELOG.md
Labels: cla: yes, ext

#576 Fix code coverage for ext packages
  .coveragerc
  nox.py
Labels: cla: yes

#581 Prepare for stackdriver stats release
  contrib/opencensus-ext-stackdriver/README.rst
  contrib/opencensus-ext-stackdriver/examples/stackdriver.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_stats.py
  tests/system/stats/stackdriver/stackdriver_stats_test.py
Labels: cla: yes

#585 Fix start time for Stackdriver Gauge metrics.
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/stats_exporter/__init__.py
Labels: bug, cla: yes, exporters

#582 Bump stackdriver ext to 0.1.1
  contrib/opencensus-ext-stackdriver/version.py
Labels: GA-Effort, cla: yes, exporters

#589 Regenerate ocagent proto files.
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/common/v1/common_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/agent/trace/v1/trace_service_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/resource/v1/resource_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/trace_config_pb2.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/gen/opencensus/trace/v1/trace_pb2.py
Labels: cla: yes, exporters, ext
