Repository census-instrumentation/opencensus-python, pull requests merged in 2019-02, with the labels that each got.

#476 Metrics: add MetricsProducer and convert stats
  opencensus/metrics/export/metric_producer.py
  opencensus/metrics/export/value.py
  opencensus/stats/aggregation_data.py
  opencensus/stats/measure_to_view_map.py
  opencensus/stats/metric_utils.py
  opencensus/stats/stats.py
  tests/unit/metrics/export/test_metric_producer.py
  tests/unit/stats/test_aggregation_data.py
  tests/unit/stats/test_stats.py
Labels: GA-Effort, cla: yes, metrics

#479 Add stats and metrics reprs
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/metric_descriptor.py
  opencensus/metrics/export/point.py
  opencensus/metrics/export/time_series.py
  opencensus/metrics/export/value.py
  opencensus/metrics/label_key.py
  opencensus/metrics/label_value.py
  opencensus/stats/aggregation_data.py
Labels: cla: yes, style

#486 Exporter/Prometheus: Convert None label values to empty string.
  opencensus/stats/exporters/prometheus_exporter.py
  tests/unit/stats/exporter/test_prometheus_stats.py
Labels: bug, cla: yes, exporters

#490 Exporter/Prometheus: Append +Inf to histogram buckets.
  opencensus/stats/exporters/prometheus_exporter.py
  tests/unit/stats/exporter/test_prometheus_stats.py
Labels: cla: yes, exporters

#495 Use consistent paths between code and tests.
  tests/unit/stats/exporters/test_base_stats.py
  tests/unit/stats/exporters/test_prometheus_stats.py
  tests/unit/stats/exporters/test_stackdriver_stats.py
Labels: cla: yes

#265 Implement B3 propagation
  opencensus/trace/propagation/b3_format.py
  opencensus/trace/span_context.py
  tests/unit/trace/propagation/test_b3_format.py
Labels: cla: yes

#493 refactor namespace package - cleanup opencensus root folder
  opencensus/__init__.py
  opencensus/common/version.py
  opencensus/stats/exporters/stackdriver_exporter.py
  opencensus/trace/exporters/ocagent/trace_exporter.py
  opencensus/trace/exporters/stackdriver_exporter.py
  setup.py
  tests/unit/stats/exporters/test_stackdriver_stats.py
  tests/unit/trace/exporters/ocagent/test_trace_exporter.py
  tests/unit/trace/exporters/test_stackdriver_exporter.py
Labels: cla: yes

#497 Fix Changelog Dates
  CHANGELOG.md
Labels: cla: yes

#494 Add gauges
  opencensus/metrics/export/gauge.py
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/time_series.py
  opencensus/metrics/export/value.py
  tests/unit/metrics/export/test_gauge.py
Labels: GA-Effort, cla: yes, metrics

#492 Exporter/Prometheus: Upgrade version and fix buckets and labels.
  CHANGELOG.md
  opencensus/stats/exporters/prometheus_exporter.py
  requirements-test.txt
  tests/system/stats/prometheus/prometheus_stats_test.py
  tests/unit/stats/exporters/test_prometheus_stats.py
Labels: bug, cla: yes, exporters

#499 Fix order in changelog.
  CHANGELOG.md
Labels: cla: yes

#501 Stats: Remove min and max from Distribution.
  CHANGELOG.md
  opencensus/stats/aggregation.py
  opencensus/stats/aggregation_data.py
  tests/unit/stats/exporters/test_stackdriver_stats.py
  tests/unit/stats/test_aggregation.py
  tests/unit/stats/test_aggregation_data.py
Labels: GA-Effort, cla: yes, stats

#496 removing exception logging in server_interceptor
  opencensus/trace/ext/grpc/server_interceptor.py
Labels: cla: yes

#498 Add derived gauges
  opencensus/common/backports.py
  opencensus/common/utils.py
  opencensus/metrics/export/gauge.py
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/time_series.py
  tests/unit/metrics/export/test_gauge.py
  tests/unit/trace/test_utils.py
Labels: GA-Effort, cla: yes, metrics

#506 Restrict people who can approve reviews. This is to ensure code quality.
  .github/CODEOWNERS
Labels: cla: yes

#503 Add gauge registry
  opencensus/metrics/export/gauge.py
  tests/unit/metrics/export/test_gauge.py
Labels: GA-Effort, cla: yes, metrics

#507 Add @songy23 to owners
  .github/CODEOWNERS
Labels: cla: yes

#508 Replace MonitoredResource with Resource
  opencensus/common/monitored_resource_util/monitored_resource.py
  opencensus/common/monitored_resource_util/monitored_resource_util.py
  opencensus/common/resource.py
  opencensus/stats/exporters/stackdriver_exporter.py
  opencensus/trace/exporters/stackdriver_exporter.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
  tests/unit/common/monitored_resource_util/test_monitored_resource_util.py
  tests/unit/common/test_resource.py
  tests/unit/stats/exporters/test_stackdriver_stats.py
  tests/unit/trace/exporters/test_stackdriver_exporter.py
Labels: cla: yes

#511 Rename monitored_resource_util package
  opencensus/common/monitored_resource/__init__.py
  opencensus/common/monitored_resource/aws_identity_doc_utils.py
  opencensus/common/monitored_resource/gcp_metadata_config.py
  opencensus/common/monitored_resource/monitored_resource.py
  opencensus/stats/exporters/stackdriver_exporter.py
  opencensus/trace/exporters/stackdriver_exporter.py
  tests/unit/common/monitored_resource_util/test_aws_identity_doc_utils.py
  tests/unit/common/monitored_resource_util/test_gcp_metadata_config.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
Labels: cla: yes

#512 Stats: Make defensive copy and set end time for ViewData when export.
  opencensus/stats/measure_to_view_map.py
  tests/unit/stats/test_measure_to_view_map.py
Labels: bug, cla: yes, stats

#513 Add support for custom resources
  opencensus/common/resource.py
  tests/unit/common/test_resource.py
Labels: GA-Effort, cla: yes, resources

#516 Value type lint fixes
  opencensus/metrics/export/point.py
  opencensus/metrics/export/value.py
  tests/unit/metrics/export/test_point.py
  tests/unit/metrics/export/test_time_series.py
  tests/unit/metrics/export/test_value.py
Labels: cla: yes, style

#518 Tracing: Add Double/Float64 Attribute.
  opencensus/trace/attributes.py
  opencensus/trace/exporters/jaeger_exporter.py
  opencensus/trace/exporters/ocagent/utils.py
  opencensus/trace/exporters/zipkin_exporter.py
  tests/unit/trace/exporters/test_jaeger_exporter.py
  tests/unit/trace/exporters/test_stackdriver_exporter.py
  tests/unit/trace/exporters/test_zipkin_exporter.py
  tests/unit/trace/test_attributes.py
Labels: GA-Effort, cla: yes, trace

#524 Regenerate ocagent proto files.
  opencensus/trace/exporters/gen/opencensus/agent/common/v1/common_pb2.py
  opencensus/trace/exporters/gen/opencensus/agent/trace/v1/trace_service_pb2.py
  opencensus/trace/exporters/gen/opencensus/agent/trace/v1/trace_service_pb2_grpc.py
  opencensus/trace/exporters/gen/opencensus/resource/__init__.py
  opencensus/trace/exporters/gen/opencensus/resource/v1/__init__.py
  opencensus/trace/exporters/gen/opencensus/resource/v1/resource_pb2.py
  opencensus/trace/exporters/gen/opencensus/trace/v1/trace_config_pb2.py
  opencensus/trace/exporters/gen/opencensus/trace/v1/trace_pb2.py
Labels: cla: yes, exporters

#521 Fix warning for 0-valued distribution boundaries
  opencensus/stats/aggregation.py
Labels: cla: yes

#526 Exporter/OcAgent: Support double attribute.
  opencensus/trace/exporters/ocagent/utils.py
  tests/unit/trace/exporters/ocagent/test_trace_exporter_utils.py
Labels: cla: yes, exporters

#523 refactor namespace package - add the first contrib package
  contrib/opencensus-common-correlationcontext/README.rst
  contrib/opencensus-common-correlationcontext/opencensus/__init__.py
  contrib/opencensus-common-correlationcontext/opencensus/common/__init__.py
  contrib/opencensus-common-correlationcontext/opencensus/common/correlationcontext/__init__.py
  contrib/opencensus-common-correlationcontext/opencensus/common/correlationcontext/correlationcontext.py
  contrib/opencensus-common-correlationcontext/setup.py
  contrib/opencensus-common-correlationcontext/tests/__init__.py
  contrib/opencensus-common-correlationcontext/tests/test_correlation_context.py
  contrib/opencensus-common-correlationcontext/version.py
Labels: cla: yes, tags

#500 Bump django to 1.11.20
  requirements-test.txt
Labels: cla: yes

#530 Replace Google in copyright boilerplate
  AUTHORS
  opencensus/common/http_handler.py
  opencensus/common/monitored_resource/aws_identity_doc_utils.py
  opencensus/common/monitored_resource/gcp_metadata_config.py
  opencensus/common/monitored_resource/monitored_resource.py
  opencensus/common/resource.py
  opencensus/trace/exporters/stackdriver_exporter.py
  opencensus/trace/tracers/__init__.py
  tests/unit/common/monitored_resource_util/test_aws_identity_doc_utils.py
  tests/unit/common/monitored_resource_util/test_gcp_metadata_config.py
  tests/unit/common/monitored_resource_util/test_monitored_resource.py
  tests/unit/common/test_http_handler.py
  tests/unit/common/test_resource.py
  tests/unit/trace/exporters/test_stackdriver_exporter.py
Labels: cla: yes

#529 refactor namespace package - cleanup opencensus.common namespace
  opencensus/common/__init__.py
  opencensus/common/backports/__init__.py
  opencensus/common/http_handler/__init__.py
  opencensus/common/resource/__init__.py
  opencensus/common/utils/__init__.py
  opencensus/common/version/__init__.py
  opencensus/trace/attributes.py
  opencensus/trace/span.py
  opencensus/trace/span_data.py
  opencensus/trace/stack_trace.py
  opencensus/trace/time_event.py
  setup.py
  tests/unit/trace/test_stack_trace.py
  tests/unit/trace/test_tracer.py
  tests/unit/trace/test_utils.py
Labels: cla: yes
