Repository census-instrumentation/opencensus-python, pull requests merged in 2019-01, with the labels that each got.

#434 Enforce str for some django attributes
  opencensus/trace/ext/django/middleware.py
Labels: cla: yes

#374 Fix: StackDriver exporter fails with "One or more Timeseries could not be written"
  examples/stats/exporter/stackdriver.py
  opencensus/common/utils.py
  opencensus/stats/exporters/stackdriver_exporter.py
  opencensus/trace/attributes.py
  opencensus/trace/exporters/jaeger_exporter.py
  opencensus/trace/exporters/zipkin_exporter.py
  opencensus/trace/span.py
  opencensus/trace/span_data.py
  opencensus/trace/stack_trace.py
  opencensus/trace/time_event.py
  tests/unit/stats/exporter/test_stackdriver_stats.py
  tests/unit/trace/test_utils.py
Labels: cla: yes

#443 Bump django to 1.11.18
  requirements-test.txt
Labels: cla: yes

#438 Fix stackdriver exporter
  opencensus/common/utils.py
  opencensus/stats/exporters/stackdriver_exporter.py
  opencensus/stats/view_data.py
  tests/unit/stats/exporter/test_stackdriver_stats.py
Labels: cla: yes

#448 allow underscores in label keys
  opencensus/stats/exporters/stackdriver_exporter.py
  tests/unit/stats/exporter/test_stackdriver_stats.py
Labels: cla: yes

#440 Fix Prometheus Stats Exporter.
  examples/stats/exporter/prometheus.py
  opencensus/stats/exporters/prometheus_exporter.py
  tests/system/stats/prometheus/prometheus_stats_test.py
  tests/unit/stats/exporter/test_prometheus_stats.py
Labels: bug, cla: yes, exporters, stats

#452 Remove deprecated transports
  README.rst
  opencensus/common/transports/async_.py
  opencensus/trace/exporters/file_exporter.py
  opencensus/trace/exporters/jaeger_exporter.py
  opencensus/trace/exporters/logging_exporter.py
  opencensus/trace/exporters/ocagent/trace_exporter.py
  opencensus/trace/exporters/print_exporter.py
  opencensus/trace/exporters/stackdriver_exporter.py
  opencensus/trace/exporters/transports/__init__.py
  opencensus/trace/exporters/transports/background_thread.py
  opencensus/trace/exporters/transports/base.py
  opencensus/trace/exporters/transports/sync.py
  opencensus/trace/exporters/zipkin_exporter.py
  opencensus/trace/ext/django/config.py
  opencensus/trace/ext/flask/flask_middleware.py
  tests/system/trace/django/app/settings.py
  tests/system/trace/flask/main.py
  tests/unit/trace/exporters/transports/test_background_thread.py
  tests/unit/trace/exporters/transports/test_base_transport.py
  tests/unit/trace/ext/django/test_config.py
  tests/unit/trace/ext/django/test_middleware.py
  tests/unit/trace/ext/pyramid/test_pyramid_middleware.py
Labels: cla: yes

#453 Stats: Fix recording with None TagMap.
  opencensus/stats/view_data.py
  tests/unit/stats/test_view_data.py
Labels: bug, cla: yes, stats

#463 Update version, add changelog
  CHANGELOG.md
  opencensus/__version__.py
Labels: cla: yes

#464 only attempt to set the span status when a current span is available
  opencensus/trace/ext/flask/flask_middleware.py
  tests/unit/trace/ext/flask/test_flask_middleware.py
Labels: cla: yes

#467 Metrics point conversion
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/metric_descriptor.py
  opencensus/metrics/export/time_series.py
  opencensus/metrics/export/value.py
  opencensus/stats/aggregation_data.py
  tests/unit/metrics/export/test_metric_descriptor.py
  tests/unit/metrics/export/test_time_series.py
  tests/unit/stats/test_aggregation_data.py
Labels: GA-Effort, cla: yes, metrics

#469 Metrics view data conversion
  opencensus/stats/measure_to_view_map.py
  opencensus/stats/metric_utils.py
  opencensus/stats/view.py
  tests/unit/stats/test_metric_utils.py
  tests/unit/stats/test_view.py
Labels: GA-Effort, cla: yes, metrics

#471 Fix typo on Readme about AsyncTransport import.
  README.rst
Labels: cla: yes

#473 minor: fix build warning and updated the metric proto link
  opencensus/metrics/export/metric.py
  opencensus/metrics/export/metric_descriptor.py
  opencensus/metrics/export/time_series.py
  opencensus/metrics/export/value.py
  opencensus/trace/tracestate.py
Labels: cla: yes

#475 Exporter/Prometheus: Sanitize metric name and key.
  opencensus/stats/exporters/prometheus_exporter.py
  tests/unit/stats/exporter/test_prometheus_stats.py
Labels: bug, cla: yes, exporters
