Repository census-instrumentation/opencensus-python, pull requests merged in 2019-08, with the labels that each got.

#741 Bump version to 0.7.0 for only packages that have changed
  context/opencensus-context/version.py
  contrib/opencensus-correlation/CHANGELOG.md
  contrib/opencensus-correlation/version.py
  contrib/opencensus-ext-dbapi/CHANGELOG.md
  contrib/opencensus-ext-dbapi/version.py
  contrib/opencensus-ext-gevent/CHANGELOG.md
  contrib/opencensus-ext-gevent/version.py
  contrib/opencensus-ext-google-cloud-clientlibs/CHANGELOG.md
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/version.py
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-grpc/version.py
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-httplib/version.py
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-jaeger/version.py
  contrib/opencensus-ext-logging/CHANGELOG.md
  contrib/opencensus-ext-logging/version.py
  contrib/opencensus-ext-mysql/CHANGELOG.md
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-mysql/version.py
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/version.py
  contrib/opencensus-ext-postgresql/CHANGELOG.md
  contrib/opencensus-ext-postgresql/version.py
  contrib/opencensus-ext-prometheus/CHANGELOG.md
  contrib/opencensus-ext-prometheus/version.py
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/version.py
  contrib/opencensus-ext-pymysql/CHANGELOG.md
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pymysql/version.py
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/version.py
  contrib/opencensus-ext-sqlalchemy/CHANGELOG.md
  contrib/opencensus-ext-sqlalchemy/version.py
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/version.py
  contrib/opencensus-ext-threading/CHANGELOG.md
  contrib/opencensus-ext-threading/version.py
  contrib/opencensus-ext-zipkin/CHANGELOG.md
  contrib/opencensus-ext-zipkin/version.py
  setup.py
Labels: cla: yes

#742 Fix CHANGELOG typo
  context/opencensus-context/CHANGELOG.md
Labels: cla: yes

#740 Bump version and Merge Changelog after 0.7.0 release
  CHANGELOG.md
  contrib/opencensus-correlation/CHANGELOG.md
  contrib/opencensus-ext-azure/CHANGELOG.md
  contrib/opencensus-ext-azure/opencensus/ext/azure/common/version.py
  contrib/opencensus-ext-azure/setup.py
  contrib/opencensus-ext-dbapi/setup.py
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-django/setup.py
  contrib/opencensus-ext-django/version.py
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-flask/version.py
  contrib/opencensus-ext-gevent/setup.py
  contrib/opencensus-ext-google-cloud-clientlibs/setup.py
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-httplib/setup.py
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-logging/setup.py
  contrib/opencensus-ext-mysql/setup.py
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-postgresql/setup.py
  contrib/opencensus-ext-prometheus/setup.py
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymysql/setup.py
  contrib/opencensus-ext-pyramid/CHANGELOG.md
  contrib/opencensus-ext-pyramid/setup.py
  contrib/opencensus-ext-pyramid/version.py
  contrib/opencensus-ext-requests/setup.py
  contrib/opencensus-ext-sqlalchemy/setup.py
  contrib/opencensus-ext-stackdriver/setup.py
  contrib/opencensus-ext-threading/setup.py
  contrib/opencensus-ext-zipkin/setup.py
  opencensus/common/version/__init__.py
Labels: cla: yes

#743 Skip existing packages on twine upload
  scripts/twine_upload.sh
Labels: cla: yes

#738 Added set_status to span, updated pymongo integration
  CHANGELOG.md
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-grpc/tests/test_server_interceptor.py
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/utils.py
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/opencensus/ext/pymongo/trace.py
  contrib/opencensus-ext-pymongo/tests/test_pymongo_trace.py
  opencensus/trace/base_span.py
  opencensus/trace/blank_span.py
  opencensus/trace/span.py
  opencensus/trace/status.py
  tests/unit/trace/test_base_span.py
  tests/unit/trace/test_blank_span.py
  tests/unit/trace/test_span.py
  tests/unit/trace/test_status.py
Labels: cla: yes

#747 Bump SD exporter package version for release
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/version.py
Labels: cla: yes

#748 Bump SD exporter package version for release
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/version.py
Labels: cla: yes

#744 Skip existing packages on twine upload
  scripts/twine_upload.sh
Labels: cla: yes

#749 Bump SD exporter to 0.7.1 for release
  CHANGELOG.md
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/setup.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-flask/version.py
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-grpc/setup.py
  contrib/opencensus-ext-grpc/tests/test_server_interceptor.py
  contrib/opencensus-ext-grpc/version.py
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py
  contrib/opencensus-ext-jaeger/setup.py
  contrib/opencensus-ext-jaeger/version.py
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/opencensus/ext/ocagent/trace_exporter/utils.py
  contrib/opencensus-ext-ocagent/setup.py
  contrib/opencensus-ext-ocagent/version.py
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-pymongo/opencensus/ext/pymongo/trace.py
  contrib/opencensus-ext-pymongo/setup.py
  contrib/opencensus-ext-pymongo/tests/test_pymongo_trace.py
  contrib/opencensus-ext-pymongo/version.py
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/setup.py
  opencensus/common/version/__init__.py
  opencensus/trace/base_span.py
  opencensus/trace/blank_span.py
  opencensus/trace/span.py
  opencensus/trace/status.py
  tests/unit/trace/test_base_span.py
  tests/unit/trace/test_blank_span.py
  tests/unit/trace/test_span.py
  tests/unit/trace/test_status.py
Labels: cla: yes

#752 Bump stackdriver to 0.7.1
  contrib/opencensus-ext-stackdriver/version.py
Labels: cla: yes

#753 Bump version for httplibs and requests to 0.7.1
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-httplib/version.py
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/version.py
Labels: cla: yes

#754 Update CHANGELOG and bump versions
  contrib/opencensus-ext-grpc/version.py
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-httplib/version.py
  contrib/opencensus-ext-jaeger/version.py
  contrib/opencensus-ext-pymongo/version.py
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/version.py
  contrib/opencensus-ext-stackdriver/version.py
Labels: cla: yes

#750 SD exporter and set_status release
  CHANGELOG.md
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-grpc/CHANGELOG.md
  contrib/opencensus-ext-jaeger/CHANGELOG.md
  contrib/opencensus-ext-ocagent/CHANGELOG.md
  contrib/opencensus-ext-ocagent/version.py
  contrib/opencensus-ext-pymongo/CHANGELOG.md
  contrib/opencensus-ext-stackdriver/CHANGELOG.md
Labels: cla: yes

#746 Requests library spec fidelity
  CHANGELOG.md
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/opencensus/ext/requests/trace.py
  contrib/opencensus-ext-requests/tests/test_requests_trace.py
  opencensus/trace/exceptions_status.py
  opencensus/trace/utils.py
  tests/unit/trace/test_exceptions_status.py
  tests/unit/trace/test_ext_utils.py
Labels: cla: yes

#756 Update codeowners file
  .github/CODEOWNERS
Labels: cla: yes

#759 Fixes value for `http.route` in Flask middleware
  contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
Labels: cla: yes

#761 Update GCP metadata URL
  opencensus/common/monitored_resource/gcp_metadata_config.py
Labels: bug, cla: yes, resources

#762 0.7.2 release
  CHANGELOG.md
  opencensus/common/monitored_resource/gcp_metadata_config.py
  opencensus/common/version/__init__.py
Labels: cla: yes, release

#763 0.7.2 changes on master
  CHANGELOG.md
Labels: cla: yes

#758 Standard Metrics - Incoming Requests Per Second
  contrib/opencensus-ext-azure/CHANGELOG.md
  contrib/opencensus-ext-azure/README.rst
  contrib/opencensus-ext-azure/opencensus/ext/azure/metrics_exporter/standard_metrics/__init__.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/metrics_exporter/standard_metrics/http_dependency.py
  contrib/opencensus-ext-azure/opencensus/ext/azure/metrics_exporter/standard_metrics/http_requests.py
  contrib/opencensus-ext-azure/tests/test_azure_standard_metrics.py
Labels: cla: yes

#770 Delete SD integ test metric descriptors
  tests/system/stats/stackdriver/stackdriver_stats_test.py
Labels: cla: yes, tech debt

#755 Hotfix/django flask pyramid status code
  CHANGELOG.md
  contrib/opencensus-ext-django/CHANGELOG.md
  contrib/opencensus-ext-django/examples/app/views.py
  contrib/opencensus-ext-django/opencensus/ext/django/middleware.py
  contrib/opencensus-ext-django/tests/test_django_middleware.py
  contrib/opencensus-ext-flask/CHANGELOG.md
  contrib/opencensus-ext-flask/opencensus/ext/flask/flask_middleware.py
  contrib/opencensus-ext-flask/tests/test_flask_middleware.py
  contrib/opencensus-ext-httplib/CHANGELOG.md
  contrib/opencensus-ext-httplib/opencensus/ext/httplib/trace.py
  contrib/opencensus-ext-pyramid/CHANGELOG.md
  contrib/opencensus-ext-pyramid/examples/app/__init__.py
  contrib/opencensus-ext-pyramid/opencensus/ext/pyramid/pyramid_middleware.py
  contrib/opencensus-ext-pyramid/tests/test_pyramid_middleware.py
  contrib/opencensus-ext-stackdriver/opencensus/ext/stackdriver/trace_exporter/__init__.py
  contrib/opencensus-ext-stackdriver/tests/test_stackdriver_exporter.py
  tests/system/trace/django/django_system_test.py
  tests/system/trace/flask/flask_system_test.py
Labels: cla: yes

#771 Fixed requests contrib to raise original exceptions
  CHANGELOG.md
  contrib/opencensus-ext-requests/CHANGELOG.md
  contrib/opencensus-ext-requests/opencensus/ext/requests/trace.py
  contrib/opencensus-ext-requests/tests/test_requests_trace.py
Labels: cla: yes

#775 Use Django 2.0 DB instrumentation
  contrib/opencensus-ext-django/opencensus/ext/django/middleware.py
  contrib/opencensus-ext-django/tests/test_django_db_middleware.py
Labels: cla: yes
